### ISSUE TITLE
Consider defaulting `watch` to true unless in production?

### ISSUE THREAD

**Issue by nfriedly** [ChrisAckerman/node-express-browserify#1]
Hey, thanks for creating this, I'm using it a lot. But almost every time I do, I end up setting up my config like so:

``` js
app.get('/js/bundle.js', expressBrowserify('./public/js/bundle.js', {
  watch: (process.env.NODE_ENV !== 'production')
}));
```

I think that this might be a good default value for `watch`: on in development, off in production.

(It might be smarter to use `app.get('env')` instead of `process.env.NODE_ENV`, but I think that requires turning it into a sub-app in order to get access to `app`, so maybe not worth the trouble...)

**Comment by ChrisAckerman** [comment]
Seems like a good idea. Want to create a pull request for the change?

**Comment by ChrisAckerman** [comment]
Closed due to no follow up.
